### ISSUE TITLE
Visible / hidden wording changes

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#104]
Visible

- [x] Change "Clear Filters" to "Clear All Filters" for clarity

- [x] Add "By" before author names (no colon) for better orientation in screen reading scenarios 

Hidden

- [x] Add hidden text right before the unordered list of tags that explains "Click to apply or remove tags"

- [x] Change button labels for applied tags from "remove filter" to "tag applied"

cc @wlla 

Referencing Accessibility section of QA Test Plan at https://docs.google.com/a/nypl.org/document/d/1nf9o_D5WkQajzOvG2LTOkNfvoANuxXevDJlsRizfqHk/edit?usp=sharing

**Comment by EdwinGuzman** [comment]
@wlla can you please check the third checkbox item? I added it in and I can see it in VO but only when I navigate using the keypad, but not tabbing.
