### ISSUE TITLE
Fix overlay issue caused by book count text

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/staff-picks#110]
@chrismulholland reported this issue that the book count text overlays on top of the Filter text.

**Comment by rhernand3z** [comment]
@chrismulholland @courtneymcgee -- can you review this so it can be closed?

http://staff-picks-dev.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/childrens

**Comment by rhernand3z** [comment]
CC: @natalietsch

**Comment by chrismulholland** [comment]
hmm... I still see the overlap, but just by 1 character.

**Comment by natalietsch** [comment]
@courtneymcgee - let us know what you think.  Thanks!

**Comment by courtneymcgee** [comment]
On PC, can't get overlap scenario on Chrome or Firefox. Overlap seems to be an edge case scenario. Let's close this issue out as it is now and call it fixed.

**Comment by EdwinGuzman** [comment]
Let's keep comment threads like these in the PRs so we can easily reference issues/confirmations where the code change is happening.
