### ISSUE TITLE
Add analytics 

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#112]

**Comment by EdwinGuzman** [comment]
@courtneymcgee we usually create a spreadsheet where we keep track of all actions and events. I created it here: https://docs.google.com/spreadsheets/d/11e52iPS_oEnkkcUOZyd7EMcZJG5DFdtzA21Hn0lWndg/edit#gid=0

I'll implement them next week but feel free to update or add any more events that should be tracked in the app.
