### ISSUE TITLE
Social media link text bug

### ISSUE THREAD

**Issue by wlla** [NYPL/staff-picks#113]
The two social media links in the Additional Information section need to be updated. Currently the text associated with these links isn't associating correctly. The social links in the universal footer are working correctly. Update the Additional information links be updated to follow the footer pattern.

**Comment by wlla** [comment]
Please also update the way the breadcrumbs svg text is associated to match the footer pattern.

**Comment by EdwinGuzman** [comment]
The only problem is that the footer pattern uses icons and not svg. Right now the svg text reads "return to" using the `title` attribute in the svg. Is that not right or what is the problem?

**Comment by wlla** [comment]
On PC, the "return to" alt for the svg isn't being announced.

The alts for the social text are getting announced now.

**Comment by EdwinGuzman** [comment]
Will keep open for the breadcrumbs svg.
