### ISSUE TITLE
Duplicated tag list label

### ISSUE THREAD

**Issue by wlla** [NYPL/staff-picks#115]
We now have a label associated with the list of tags, however, the label is formatted as a visually hidden span which is then referenced by the label. This causes the text to be repeated when moving down the page sequentially. Review usability.

**Comment by EdwinGuzman** [comment]
This is the DOM that's in question:
![screen shot 2017-11-13 at 2 35 47 pm](https://user-images.githubusercontent.com/1280564/32745192-f3f192ce-c87f-11e7-9d48-f6fda6801d9c.png)

Would it make sense to have

```
  <ul aria-label="Click to apply or remove tags.">
```

instead of a separate `<span>` for the label?

**Comment by wlla** [comment]
That should fix it. Or, if Courtney is okay with the copy change. Could just give the `h2` an id and have the `aria-labelledby` of the `ul` point to that and remove the visually hidden span? That would mean that the unordered list of tags would be labelled "filter by tags".

**Comment by EdwinGuzman** [comment]
Okay, I'm deploying that update right now to production. If it doesn't work and @courtneymcgee thinks it's okay, we can try the second method you pointed out.

**Comment by wlla** [comment]
Looks good to me. Ready to close out this issue?

**Comment by EdwinGuzman** [comment]
yes
