### ISSUE TITLE
Aria-live issues with Jaws/Chrome

### ISSUE THREAD

**Issue by wlla** [NYPL/staff-picks#117]
The total books found `aria-live` region has a delay when using Jaws and Chrome on a PC. The number announced is the number for the region version immediately preceding. Functionality is working correctly in Jaws/IE/Firefox, VoiceOver/Safari, and mobile (Android + iOS).

**Comment by EdwinGuzman** [comment]
Could be related to #114. Check out the resource. It could be a specific version and browser that's the issue we cannot readily solve.

**Comment by seanredmond** [comment]
I see the same thing happening with Chrome and VoiceOver. I looks to me like VoiceOver is quicker on the draw than the DOM changes?
