### ISSUE TITLE
Confirm copy for accordion control

### ISSUE THREAD

**Issue by wlla** [NYPL/staff-picks#119]
In mobile view, the button controlling the accordion expansion and collapse is labelled; creating a ticket to confirm that this is final copy.

Current label:
When accordion is closed, svg span is "Expand"; which announces as "Expand collapsed button"
When accordion is open, svg span is "Collapse"; which announces as "Collapse expanded button"

Courtney to review and supply updated copy if needed.

**Comment by courtneymcgee** [comment]
Sounds/looks good! This is ready for a dev to claim.

**Comment by wlla** [comment]
That's the current copy so no additional action is needed, I think.

**Comment by courtneymcgee** [comment]
Was asked by @wlla and @rhernand3z to further review expand/collapse language. This is tricky, as different combinations of browsers and readers produce different results. 

Generally, the larger experience context for this is:

- "Filter by tags"
- "[X] books found"
- _some expand/collapse language_
- "Click to apply or remove tags"

On that third bullet, we can give more clarity and direction. Let's go with "Expand tag list" and "Collapse tag list" (if that works for both of you)! I believe that means they'll be announced as "Expand tag list button" and "Collapse tag list button."

**Comment by rhernand3z** [comment]
Closing, merged #125
