### ISSUE TITLE
"found" cut off on small displays, as in "100 books foun"

### ISSUE THREAD

**Issue by chrismulholland** [NYPL/staff-picks#129]
![image](https://user-images.githubusercontent.com/1929170/32846993-c28d680c-c9f6-11e7-869d-e64cf4f5a97c.png)

**Comment by natalietsch** [comment]
@chrismulholland I think this duplicates #128 from @courtneymcgee.

**Comment by chrismulholland** [comment]
yeah, I wasn't certain which issue Courtney was pointing out in her post.

**Comment by EdwinGuzman** [comment]
Duplicate. Closing this one.
