### ISSUE TITLE
Punch up h1 title / p description text in banner

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#130]
Will seek estimate from @EdwinGuzman and design guidance from @ricardoom to determine if we'll address this. 

This would be a response to feedback from stakeholders that the banner text seemed "plain."

We might make the h1 bold or put it in Milo.

**Comment by EdwinGuzman** [comment]
I don't think we have `MiloSlab-Light`.

Here are what are available:

* https://bitbucket.org/NYPL/dgx-header-component/src/b0bdc31d037c99292a63ca3c47bff416ce56619b/src/styles/utils/_fonts.scss?at=master&fileviewer=file-view-default
* There's this one in the Staff Picks app but it's not being used: https://github.com/NYPL/staff-picks/blob/master/src/client/styles/utils/_fonts.scss

**Comment by EdwinGuzman** [comment]
When I tried it, I got this:

![screen shot 2017-11-15 at 12 46 09 pm](https://user-images.githubusercontent.com/1280564/32851454-fe41447a-ca02-11e7-9389-6590ce3a9a67.png)

**Comment by ricardoom** [comment]
@EdwinGuzman please try `Milo-Medium` thinking we might have contrast issues w/ the light version...
