### ISSUE TITLE
Update route for Annual lists

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/staff-picks#2]
Update `/books-music-dvds/recommendations/best-year/annual/:list` to the new url specified by @courtneymcgee. The `:list` param is either `childrens` or `ya`.

Check `src/app/routes/routes.jsx` to see where to make this update, and make sure that it's based off the config.

CC @courtneymcgee

**Comment by kfriedman** [comment]
Spoke with @courtneymcgee. 

Confirmed the new base URL will be:
`/books-music-dvds/recommendations/best-books`

Additional, path parameters will be added as follows:

`/books-music-dvds/recommendations/{list-type}` ➡️  `/books-music-dvds/recommendations/childrens` 

`/books-music-dvds/recommendations/{list-type}/{list-year}` ➡️  `/books-music-dvds/recommendations/childrens/2016` 

... and additional parameters may be appended.

**Comment by kfriedman** [comment]
I should also add: we eventually will need to account for the app to handle the existing *Staff Picks* URL pattern at:

`/books-music-dvds/recommendations/staff-picks/{list-date}` ➡️ 
`/books-music-dvds/recommendations/staff-picks/2017-06-01`

**Comment by EdwinGuzman** [comment]
Yup, it already does handle the existing Staff Picks (it can be cleaner though). But you can be able to update the route without affecting the previous state.
