### ISSUE TITLE
Adjustments to headers

### ISSUE THREAD

**Issue by wlla** [NYPL/staff-picks#59]
- [x] In the Hero, the text "RECOMMENDATIONS" is an `h3`. It should be an `p`. (It is being removed, but I am creating a separate ticket for that because there may be visual design implications.

- [x] In the Hero, the text "Best Books for Teens" (`data-reactid="173"`) is a `p`. It should be `h1`.

- [x] In Book cards, the titles (`class="book-item-title"`) are `h4`, they should be `h3`.

- [x] Currently, "Additional Information" (`data-reactid="3068"`) is an `h3`. Should be an `h2`. (This duplicates a comment in the PR #51.)

**Comment by rhernand3z** [comment]
@wlla -- I adjusted the `book-item-title` from an `h4` to an `h3` in #69 
@ricardoom @wlla - I've also removed the `<a>` tag in the title in #69

**Comment by EdwinGuzman** [comment]
Closing. All the tasks are complete.
