### ISSUE TITLE
Adjust Additional Information section

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#71]
For large viewports, the sentence "Many of these titles are available in formats for [patrons with print disabilities](https://www.nypl.org/accessibility/print-disabilities)." should appear on one line. As-is, it wraps kind of strangely.

Let's add in the Facebook and Twitter icons while we're at it. (Yeah!)

**Comment by EdwinGuzman** [comment]
Wrapped it because that's how it was in the design.

@ricardoom , do you have the icons ready?
