### ISSUE TITLE
Special characters misrendering (accents) - First Rule of Punk

### ISSUE THREAD

**Issue by RobKelley** [NYPL/staff-picks#74]
It seems like the accented characters in the spreadsheet aren't rendering nicely./ 
 ![image](https://user-images.githubusercontent.com/145462/32286130-dc6fe1ea-bf02-11e7-8d6d-cfd9d0af7a79.png)

Spot in Spreadsheet
https://docs.google.com/spreadsheets/d/15BZdCP-wlPZIfUYcU4PssrOcFGXDT-6qM6m0l3dwWBg/edit#gid=832466013

**Comment by ricardoom** [comment]
data entry error

Ricardo E. Gálvez | The New York Public Library
Visual Designer

Digital Experience
212.621.0521
2nd Floor-South Court
Stephen A. Schwarzman Building
476 Fifth Ave.
New York, NY 10018-2788
ricardogalvez@nypl.org


Inspiring Lifelong Learning | Advancing Knowledge | Strengthening our Communities

**Comment by courtneymcgee** [comment]
I believe @nonword fixed this up yesterday, but it now appears to be unfixed. Perhaps that happened when I re-published the data.

**Comment by EdwinGuzman** [comment]
Hmm maybe. Haven't noticed it fixed though. @RobKelley this ticket is more of an API ticket than app ticket.

**Comment by nonword** [comment]
I think maybe the kids list just needs to be re-published. Looks like the last time it was published may have been *after* I got around to deploying the fix. (I fixed the the encoding in the teens list manually, but was slow to deploy the fix.)

**Comment by courtneymcgee** [comment]
Publishing error! Will work out with Paul via Slack... 
Stay tuned!

**Comment by EdwinGuzman** [comment]
Closing.
