### ISSUE TITLE
Fix filter text overflow

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#78]
@ricardoom can provide a link that shows how text should be treated on the filter buttons to prevent overflow / weird wrapping issues.

**Comment by ricardoom** [comment]
here's something: 

![A long filter name for the button](https://github.com/NYPL/nypl-bestbooks-2017/blob/master/.exportedArtboards/basiccard/module%20/%20filters%20larger%20filter%20set.png)
