### ISSUE TITLE
Refine Clear Filters button

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#80]
@ricardoom to recommend final button sizing refinements

We'll also need to change the text from all caps to "Clear Filters"

Note for the future: _If it's in all caps, it probably shouldn't be!_ :)

**Comment by EdwinGuzman** [comment]
@ricardoom any more recommendations for what's on dev now?

**Comment by ricardoom** [comment]
working w/ Edwin on minor improvements...
