### ISSUE TITLE
Display illustrator and translator info

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#91]
Kids examples:

The Alphabet Thief
Bill Richardson
Illustrator Roxanna Bikadoroff

Bertolt	
Jacques Goldstyn	
Translator Claudia Zoe Bedrick

The Golem of Prague
Irène Cohen-Janca
Illustrator Maurizio A.C. Quarello	
Translator Brigitte Waisburg

Data at https://drive.google.com/open?id=15BZdCP-wlPZIfUYcU4PssrOcFGXDT-6qM6m0l3dwWBg

**Comment by courtneymcgee** [comment]
To clarify display, let's use this:

[title]
[author]
Illustrated by [illustrator]
Translated by [translator]

The Golem of Prague
Irène Cohen-Janca
Illustrated by Maurizio A.C. Quarello
Translated by Brigitte Waisburg

cc @ricardoom

**Comment by rhernand3z** [comment]
Closed, fixed in #93
