### ISSUE TITLE
Tags: Mitigate flicker, de-hypenate, add label

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#98]
For the visibly hidden tags, we need to:

- [x] Mitigate the way they flicker, appear/disappear 
(The first attempt was a fade treatment. Are there other approaches to consider?)
- [x] Label them "Tags: "
- [x] De-hyphenate

**Comment by ricardoom** [comment]
Or just expose them for everyone all the time... add our tag svg icon and call it a day...

![tag icon](https://user-images.githubusercontent.com/20174701/32512131-0168ca8c-c3c4-11e7-9b00-c9ec3a8362ef.png)

**Comment by courtneymcgee** [comment]
If it isn't feasible to satisfactorily mitigate in a timely fashion, then yes, @ricardoom. Then I'll go back to stakeholders and explain. This was a specific request of theirs, though, so I want to make one more good try at it.

**Comment by EdwinGuzman** [comment]
@courtneymcgee I temporarily added what I was testing on production but it's not 100% reliable. http://staff-picks-production.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/ya

**Comment by courtneymcgee** [comment]
@EdwinGuzman, that is looking pretty good! By which I mean it's barely there! Can we push it any more in terms of speed or transparency?
