### ISSUE TITLE
Clear Filters doesn’t look like a button on phone/tablet viewports

### ISSUE THREAD

**Issue by courtneymcgee** [NYPL/staff-picks#99]
@chrismulholland picked this up in testing. I've taken a look and it does look pretty stretched / non-button-y at various mobile sizes. @ricardoom, can you check it out and make a recommendation?

**Comment by ricardoom** [comment]
guh. this complicates things... I want to wait for @EdwinGuzman to finish the collapse / expand functionality before I go to far w/ this... but we might need to do something like this, so it doesnt look so bad at interim breakpoints (i.e: rando tablet resolutions)

![screen shot 2017-11-07 at 12 45 57 pm](https://user-images.githubusercontent.com/20174701/32508902-d108d2d8-c3b9-11e7-93fe-fcad42122e08.png)
![screen shot 2017-11-07 at 12 45 49 pm](https://user-images.githubusercontent.com/20174701/32508903-d11d0e92-c3b9-11e7-9e66-7552e0ef6341.png)
![screen shot 2017-11-07 at 12 44 58 pm](https://user-images.githubusercontent.com/20174701/32508904-d12c9c4a-c3b9-11e7-8b3b-e2d1c64afce1.png)

**Comment by EdwinGuzman** [comment]
That looks fine. By the way, @rhernand3z is assigned to the collapsable functionality.

**Comment by ricardoom** [comment]
@EdwinGuzman updated previous comment.
